import { useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import type { Exercise, ProgramEndBehavior, ProgramWeek, ProgramWorkout, ProgramWorkoutExerciseOverride, WorkoutTemplate, WorkoutTemplateExercise } from "../db/types";
import { addProgramWeek, addWorkoutToProgramWeek, clearProgramWorkoutExerciseOverride, createProgram, deleteProgram, deleteProgramWeek, duplicateProgramWeek, getProgramEditorData, getPrograms, moveProgramWeek, moveProgramWorkout, removeProgramWorkout, updateProgram, updateProgramWeek, updateProgramWorkout, upsertProgramWorkoutExerciseOverride, type OverrideChanges } from "../data/programRepository";
import { getWorkoutTemplates } from "../data/templateRepository";

const optionalNumber = (value: string) => value.trim() === "" ? undefined : Number(value);
const show = (value: number | string | undefined) => value === undefined || value === "" ? "—" : value;

function OverrideEditor({ workout, templateExercises, overrides, exercises }: { workout: ProgramWorkout; templateExercises: WorkoutTemplateExercise[]; overrides: ProgramWorkoutExerciseOverride[]; exercises: Exercise[] }) {
  if (!templateExercises.length) return <p className="muted">This template has no exercises.</p>;
  return <div className="program-override-list">{templateExercises.map(templateExercise => {
    const override = overrides.find(row => row.exerciseId === templateExercise.exerciseId);
    return <OverrideExercise key={templateExercise.id} workoutId={workout.id!} templateExercise={templateExercise} override={override} exerciseName={exercises.find(e=>e.id===templateExercise.exerciseId)?.name ?? "Unknown exercise"} />;
  })}</div>;
}

function OverrideExercise({ workoutId, templateExercise, override, exerciseName }: { workoutId:number; templateExercise:WorkoutTemplateExercise; override?:ProgramWorkoutExerciseOverride; exerciseName:string }) {
  const [fields,setFields]=useState(() => ({ plannedSetCount: override?.plannedSetCount?.toString()??"", targetMinReps:override?.targetMinReps?.toString()??"", targetMaxReps:override?.targetMaxReps?.toString()??"", targetRpeMin:override?.targetRpeMin?.toString()??"", targetRpeMax:override?.targetRpeMax?.toString()??"", targetRestSeconds:override?.targetRestSeconds?.toString()??"", warmupInstructions:override?.warmupInstructions??"", prescriptionNotes:override?.prescriptionNotes??"" }));
  const set=(key:keyof typeof fields,value:string)=>setFields(current=>({...current,[key]:value}));
  async function save(){const changes:OverrideChanges={plannedSetCount:optionalNumber(fields.plannedSetCount),targetMinReps:optionalNumber(fields.targetMinReps),targetMaxReps:optionalNumber(fields.targetMaxReps),targetRpeMin:optionalNumber(fields.targetRpeMin),targetRpeMax:optionalNumber(fields.targetRpeMax),targetRestSeconds:optionalNumber(fields.targetRestSeconds),warmupInstructions:fields.warmupInstructions,prescriptionNotes:fields.prescriptionNotes};if(Object.values(changes).every(v=>v===undefined||v==="")){await clear();return;}if(Object.values(changes).some(v=>typeof v==="number"&&!Number.isFinite(v)))return alert("Override values must be valid numbers.");await upsertProgramWorkoutExerciseOverride(workoutId,templateExercise.exerciseId,changes);}
  async function clear(){await clearProgramWorkoutExerciseOverride(workoutId,templateExercise.exerciseId);setFields({plannedSetCount:"",targetMinReps:"",targetMaxReps:"",targetRpeMin:"",targetRpeMax:"",targetRestSeconds:"",warmupInstructions:"",prescriptionNotes:""});}
  return <details className="program-override-card"><summary><strong>{exerciseName}</strong><span className={override?"override-badge":"muted"}>{override?"Overridden":"Inherited"}</span></summary><p className="muted">Template: {show(templateExercise.plannedSetCount)} sets · {show(templateExercise.targetMinReps)}–{show(templateExercise.targetMaxReps)} reps · RPE {show(templateExercise.targetRpeMin)}–{show(templateExercise.targetRpeMax)} · Rest {show(templateExercise.targetRestSeconds)}s</p><div className="template-target-grid">{([['plannedSetCount','Sets'],['targetMinReps','Min reps'],['targetMaxReps','Max reps'],['targetRpeMin','Min RPE'],['targetRpeMax','Max RPE'],['targetRestSeconds','Rest seconds']] as const).map(([key,label])=><label className="field-label" key={key}>{label}<input inputMode="decimal" value={fields[key]} onChange={e=>set(key,e.target.value)} placeholder={`Inherit (${show(templateExercise[key])})`}/></label>)}</div><label className="field-label">Warmup override<textarea value={fields.warmupInstructions} onChange={e=>set('warmupInstructions',e.target.value)} placeholder={templateExercise.warmupInstructions||"Inherit template"}/></label><label className="field-label">Notes override<textarea value={fields.prescriptionNotes} onChange={e=>set('prescriptionNotes',e.target.value)} placeholder={templateExercise.prescriptionNotes||"Inherit template"}/></label><div className="button-row"><button type="button" onClick={save}>Save Overrides</button><button type="button" className="secondary-button" onClick={clear}>Clear Overrides</button></div></details>;
}

function WorkoutSlot({ workout, templates, templateExercises, overrides, exercises, index, count }: { workout:ProgramWorkout & { template?: WorkoutTemplate };templates:WorkoutTemplate[];templateExercises:WorkoutTemplateExercise[];overrides:ProgramWorkoutExerciseOverride[];exercises:Exercise[];index:number;count:number }){
 const [templateId,setTemplateId]=useState(workout.templateId.toString()),[name,setName]=useState(workout.displayName??""),[notes,setNotes]=useState(workout.notes??"");
 async function save(){await updateProgramWorkout(workout.id!,{templateId:Number(templateId),displayName:name,notes});}
 const obsoleteOverrideCount=overrides.filter(override=>!templateExercises.some(exercise=>exercise.exerciseId===override.exerciseId)).length;
 return <div className="mini-card program-workout-card"><div className="program-item-heading"><strong>Workout {workout.order}: {workout.template?.name ?? "Missing template"}</strong><div className="button-row"><button className="secondary-button tiny-button" disabled={index===0} onClick={()=>moveProgramWorkout(workout.id!,"up")}>Up</button><button className="secondary-button tiny-button" disabled={index===count-1} onClick={()=>moveProgramWorkout(workout.id!,"down")}>Down</button><button className="secondary-button danger tiny-button" onClick={()=>confirm("Remove this workout slot?")&&removeProgramWorkout(workout.id!)}>Remove</button></div></div><label className="field-label">Template<select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field-label">Display name (optional)<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field-label">Slot notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button type="button" className="secondary-button" onClick={save}>Save Slot</button>{obsoleteOverrideCount>0&&<p className="muted">{obsoleteOverrideCount} obsolete override {obsoleteOverrideCount===1?"is":"are"} ignored because the exercise is no longer in this template.</p>}<details className="override-disclosure"><summary>Edit exercise overrides ({overrides.length-obsoleteOverrideCount})</summary><OverrideEditor workout={workout} templateExercises={templateExercises} overrides={overrides} exercises={exercises}/></details></div>;
}

function WeekEditor({ week, templates, exercises, index, count }: { week:ProgramWeek & {workouts:Array<ProgramWorkout & {template?:WorkoutTemplate;templateExercises:WorkoutTemplateExercise[];overrides:ProgramWorkoutExerciseOverride[]}>};templates:WorkoutTemplate[];exercises:Exercise[];index:number;count:number }){
 const [name,setName]=useState(week.name??""),[notes,setNotes]=useState(week.notes??""),[templateId,setTemplateId]=useState(templates[0]?.id?.toString()??"");
 return <details className="card program-week" open={index===0}><summary><strong>{week.name || `Week ${week.order}`}</strong><span className="muted">{week.workouts.length} workout{week.workouts.length===1?"":"s"}</span></summary><div className="button-row program-order-controls"><button className="secondary-button tiny-button" disabled={index===0} onClick={()=>moveProgramWeek(week.id!,"up")}>Move Up</button><button className="secondary-button tiny-button" disabled={index===count-1} onClick={()=>moveProgramWeek(week.id!,"down")}>Move Down</button><button className="secondary-button tiny-button" onClick={()=>duplicateProgramWeek(week.id!)}>Duplicate</button><button className="secondary-button danger tiny-button" onClick={()=>confirm("Delete this week and its workout slots?")&&deleteProgramWeek(week.id!)}>Delete</button></div><label className="field-label">Week label (optional)<input value={name} onChange={e=>setName(e.target.value)} placeholder={`Week ${week.order}`}/></label><label className="field-label">Week notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="secondary-button" onClick={()=>updateProgramWeek(week.id!,{name,notes})}>Save Week</button><div className="program-workout-list">{week.workouts.map((w,i)=><WorkoutSlot key={`${w.id}-${w.updatedAt}`} workout={w} templates={templates} templateExercises={w.templateExercises} overrides={w.overrides} exercises={exercises} index={i} count={week.workouts.length}/>)}</div>{templates.length?<div className="inline-form program-add-workout"><select value={templateId} onChange={e=>setTemplateId(e.target.value)} aria-label="Template for new workout slot">{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={()=>templateId&&addWorkoutToProgramWeek(week.id!,Number(templateId))}>Add Workout</button></div>:<p className="muted">Create a workout template before adding workout slots.</p>}</details>;
}

function ProgramDetails({ program, onDeleted }:{program:{id?:number;name:string;notes?:string;endBehavior:ProgramEndBehavior};onDeleted:()=>void}){
 const [name,setName]=useState(program.name),[notes,setNotes]=useState(program.notes??""),[endBehavior,setEndBehavior]=useState<ProgramEndBehavior>(program.endBehavior??"stop");
 async function save(){if(!program.id)return;try{await updateProgram(program.id,{name,notes,endBehavior})}catch(error){alert(error instanceof Error?error.message:"Program could not be saved.")}}
 return <div className="card"><div className="template-editor-heading"><h3>Program Details</h3><button className="secondary-button danger" onClick={()=>{if(program.id&&confirm(`Delete program "${program.name}"?`)){deleteProgram(program.id);onDeleted()}}}>Delete Program</button></div><label className="field-label">Program name<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field-label">Program notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="field-label">After final week<select value={endBehavior} onChange={e=>setEndBehavior(e.target.value as ProgramEndBehavior)}><option value="stop">Stop</option><option value="repeat">Repeat from Week 1</option><option value="continue_last_week">Continue final week</option></select></label><button onClick={save}>Save Program Details</button></div>;
}

export function ProgramEditor({ exercises }:{exercises:Exercise[]}){
 const [newName,setNewName]=useState(""),[selectedId,setSelectedId]=useState<number|null>(null);
 const programs=useLiveQuery(()=>getPrograms(),[]),templates=useLiveQuery(()=>getWorkoutTemplates(),[]);
 const effectiveSelectedId=selectedId ?? programs?.[0]?.id ?? null;
 const data=useLiveQuery(()=>effectiveSelectedId?getProgramEditorData(effectiveSelectedId):Promise.resolve(null),[effectiveSelectedId]);
 async function create(e:React.FormEvent){e.preventDefault();try{const id=await createProgram(newName);setNewName("");setSelectedId(id)}catch(error){alert(error instanceof Error?error.message:"Program could not be created.")}}
 return <section><h2>Programs</h2><div className="card"><h3>Create Program</h3><form className="inline-form" onSubmit={create}><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Strength Block, Hypertrophy, etc."/><button>Create Program</button></form></div>{programs?.length?<div className="template-layout"><div className="template-list">{programs.map(p=><button className={`template-list-item ${effectiveSelectedId===p.id?"selected-template-item":""}`} key={p.id} onClick={()=>setSelectedId(p.id??null)}>{p.name}</button>)}</div><div className="template-editor-panel">{data&&<><ProgramDetails key={`${data.program.id}-${data.program.updatedAt}`} program={data.program} onDeleted={()=>setSelectedId(null)}/>{data.weeks.map((week,i)=><WeekEditor key={`${week.id}-${week.updatedAt}`} week={week} templates={templates??[]} exercises={exercises} index={i} count={data.weeks.length}/>)}{!data.weeks.length&&<p className="card">This program has no weeks yet.</p>}<button className="add-program-week" onClick={()=>addProgramWeek(data.program.id!)}>+ Add Week</button></>}</div></div>:<p>No programs have been created yet.</p>}</section>;
}
